---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - iam.aws.edenlab.io
  resources:
  - awsiamprovisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.aws.edenlab.io
  resources:
  - awsiamprovisions/finalizers
  verbs:
  - update
- apiGroups:
  - iam.aws.edenlab.io
  resources:
  - awsiamprovisions/status
  verbs:
  - get
  - patch
  - update
