apiVersion: iam.aws.edenlab.io/v1alpha1
kind: AWSIAMProvision
metadata:
  labels:
    app.kubernetes.io/name: aws-iam-provisioner
    app.kubernetes.io/managed-by: kustomize
  name: awsiamprovision-sample
spec:
  # TODO(user): Add fields here
